### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by Gorusuke** [KevinAndresG/Formulario_Mascotas#1]
Muchach@s muy buena presentacion del ejercicio. Quiero felicitarlos por la UI porque me parece que va muy acorde con lo requerido. Estuve viendo el codigo y vi que utilizaron `Typescript` lo cual es algo que me gusto mucho sin embargo vi que tiparon los eventos con `any` y para mi eso es como hacer trampas. En un proyecto real, el any no lo utilizaran (se los digo pa que no se acostumbren al any). Por otro lado tambien les falto componetizar el form y las card. Recuerden que la componetizacion es lo que hace a `react` una gran libreria. Aparte de eso la app cumple con todos los requisitos que pedimos y me parecio muy interesante el uso del local storage para almacenar y las cards. Les criticare que se puede "eliminar" la card en la app pero cuando recargo aparece, les falto removerlas del localStorage. Aparte de eso, nada mas que agregar, **`Felicitaciones!!`**
Sigan asi! ❤

**Comment by KevinAndresG** [comment]
x
